### ISSUE TITLE
middleware client side protect my dashboard urls problem. 

### ISSUE THREAD

**Issue by mydidefix** [ctwhome/top-nuxt3#15]
middleware client side protect my dashboard urls problem.
 How do i have to change in nuxt.config.ts
enter the route, instructions from the vue2 and vue3 website do not work. Do i need to install the vue-router package. 
The goal is to protect all routes with client side middleware which have dashboard in uri. For example
/dashboard-name-id or /dashboard/person
Otherwise everything works great, the best fullstack starter package I know. 
Great work.
with kind regards

**Comment by ctwhome** [comment]
In principle, you don't need to install anything. I have a middleware that protects the routes like this:

middleware/auth.ts
```js
import { isLoggedIn } from '~/api/auth'

export default function ({ redirect }) {
  if (!isLoggedIn.value) {
    console.error('Protected Route')
    return redirect('/')
  }
}
```

On your page.vue just add:
```js
export default {
...
  middleware: ['auth'],
...
```


I didn't test it yet with Nuxt 3 tho, please let me know if that works and if so feel free to close the issue
thanks

**Comment by mydidefix** [comment]
Ok, thanks for the quick reply, I will give it a try. A few things are still unclear to me, but I'll try around.  Question wouldn't it be a good and important occasion to build such a module directly into your program. I think with Fullstack everyone needs protected routes with middleware.
Then the people could already work with it and who does not need it deactivates the module halt. I think it would be more helpful because more people use it than Fullstack Starter Package.
I will recommend your program.

**Comment by mydidefix** [comment]
I've tried a few things now, apparently it doesn't work in Nuxt3. It is not possible to run middleware via an external .ts file via export function.
Unfortunately I can't use your system with me, although you made a super starter package. I urgently need middleware in nuxt3.
with kind regards

**Comment by ctwhome** [comment]
I might recommend to take a look at my other build with nuxt 2,
https://github.com/ctwhome/top-nuxt
it has been a slow progress with nuxt 3

**Comment by mydidefix** [comment]
Thanks for your help, the problem is that neither router.push or redirect nor the installation of my Pinia module really works.
Apparently there are still too many problems with nuxt3.
I can't import modules like location or router in the auth.ts file and then use it in the default function
in the default function.
I think it is very important that in the fullstack the module mittleware is present.
Does it work with your program with nuxt3 ?



> Am 11.02.2022 um 22:34 schrieb J. Gonzalez ***@***.***>:
> 
> 
> I might recommend to take a look at my other build with nuxt 2,
> https://github.com/ctwhome/top-nuxt
> it has been a slow progress with nuxt 3
>

**Comment by PMLS3** [comment]
> I've tried a few things now, apparently it doesn't work in Nuxt3. It is not possible to run middleware via an external .ts file via export function.
> 
> Unfortunately I can't use your system with me, although you made a super starter package. I urgently need middleware in nuxt3.
> 
> with kind regards

Middleware support has been added: https://twitter.com/Atinux/status/1492134648733913089

**Comment by mydidefix** [comment]
Ok, thank you for the info.
I have now tried the script see link in your program, but it does not run.
There are a few methods missing. It may be that it is due to the version of your program. It is already about 1 month old.

https://stackblitz.com/edit/nuxt-starter-eqwqp8?file=pages%2Findex.vue <https://stackblitz.com/edit/nuxt-starter-eqwqp8?file=pages/index.vue>

Error with:
ReferenceError: definePageMeta is not defined 

TS2304: Cannot find name 'defineNuxtRouteMiddleware‘. in  middleware/auth.ts file
TS2552: Cannot find name 'navigateTo'. Did you mean 'navigator‘?  in  middleware/auth.ts file

Seemingly missing functions and packages
 I will now reinstall your program and then try. I will keep you informed if it works.

 Thank you and best regards

**Comment by ctwhome** [comment]
I have it working, ill update it in a few minutes

**Comment by ctwhome** [comment]
you can check it now here: https://github.com/ctwhome/top-nuxt3/blob/main/middleware/auth.ts

![image](https://user-images.githubusercontent.com/4195550/153709729-70ba0151-7724-4023-b516-26acaec33c84.png)

**Comment by mydidefix** [comment]
Super thanks for the quick help,
I will definitely recommend your project.
I think you have the best starter package on the market.
Dieter

**Comment by ctwhome** [comment]
I really want to make a starter that contains all the basics for modern webs :)!
